### PR TITLE
Clean dataset folder

### PR DESCRIPTION
**Pull request by HaydenMcT**
Adds documentation of data sources (and removes a dataset that was just for debugging).

### CODE REVIEW

**Review by chudizhong — APPROVED** [review]
Looks good. Approved

**Review by chudizhong — APPROVED** [review]
Approved

**Review by margoseltzer — APPROVED** [review]
Looks great to me.

**Comment by HaydenMcT** [comment]
(closed because we did a separate PR with the same changes - had some bugs with signed commits on this one)

**Pull request closed without merging**
